### ISSUE TITLE
problem with texture render 2d

### ISSUE THREAD

**Issue by tonixhouse** [AleDel/Spout-UE4#22]
Hi! have a one question to you - can't resolved this problem:

on the UE4 display have scene with light, but in Spout scene i received picture without light.
(this from Scene_capture to2d -to target capture method)
![question](https://cloud.githubusercontent.com/assets/25355972/22406769/b7cae06c-e661-11e6-818b-0fa367e55069.jpg)
But if i render Viewport (not from texture render) - all is good.
What i need to do?

**Comment by wuzelwazel** [comment]
I believe this is a gamma issue. You should be able to fix it either by switching the scene capture to the tonemapped final color instead of scene color, or by adjusting the gamma to around 2.2 in Touch Designer.

The second method is less precise but can maintain floating point values if that's desirable.

**Comment by tonixhouse** [comment]
How i can switching the scene capture to the tonemapped final color instead of scene color?

**Comment by wuzelwazel** [comment]
On the scene capture component there is a Capture Source drop down just below where you assign the texture target. Switch this to Final Color (LDR).

**Comment by tonixhouse** [comment]
It is works! Thank you very much!
